name = "brawldraftbot"
main = "./src/server.js"
compatibility_date="2023-05-18"

# [secrets]
# DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
# DISCORD_PUBLIC_KEY=${{ secrets.DISCORD_PUBLIC_KEY }}
# DISCORD_APPLICATION_ID=${{ secrets.DISCORD_APPLICATION_ID }}
# GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
